### PR TITLE
Feature/config

### PR DESCRIPTION
**Pull request by KHShadowrunner**
Initial pull request to add an items list and modify code to list out items that drop.

### CODE REVIEW

**Comment by ThauEx** [comment]
Thanks for your work. I played a little bit around with your code and cleaned it a little bit up:
https://gist.github.com/ThauEx/3d2126d72985c62a3342
What I've noticed, is that we are missing a mapping for the potions. ATM there is just an ID (like \type: 22)

**Comment by ThauEx** [comment]
I just noticed, that the drop list can be uncomplete, when an enemy drops more than one item or gold. (In my code)

**Comment by KHShadowrunner** [comment]
I might have witnessed it myself. A little tied up right now but I'll see
what I can find. I thought I caught that exception but maybe not :(

Kristopher Hutley
404-630-2584
khutley@gmail.com

"No man can stand upon the shoulders of the titans without the countless
people who helped him build the ladder."

**Comment by KHShadowrunner** [comment]
To answer, in your code the problem is that you are declaring gold and non-gold to the same variable. Since the most a single monster can drop is both gold and an item, you might want to declare the gold as a different variable. Then you could push them both? We could add another column to the table for Gold (before drops) and display even if it's 0 I guess. That's your call.

**Comment by ThauEx** [comment]
Yeah, you are right. Do you have a dump with these data, so I can test it?

**Comment by KHShadowrunner** [comment]
I have one, but I do not have a way of getting it to you. I'll upload it as a file in the tests folder.

**Comment by KHShadowrunner** [comment]
Have a screenshot of the potion list attached. I'll add a space, and maybe we can do something to make it look a little nicer, but there you go. 
change to round drops

**Comment by KHShadowrunner** [comment]
As an FYI, I've confirmed the issue I mentioned before - if a boss has multiple phases (or sub bosses?), we are not picking up the item drops from it. As an example: 

Via Purifico Maze - Inner Chamber Final boss is technically 3 aeons, but instead the enemy is listed as Pterya. no drops (but got a Greater Non-Elemental Orb). 

I have the dump saved and am looking into it, but just wanted to let you know.

**Comment by ThauEx** [comment]
Can you provide me your dump? I will try to have a look.

**Comment by KHShadowrunner** [comment]
Added to the tests folder of the pull request. Named morphing boss

**Comment by ThauEx** [comment]
A small suggestion:
change
```
      var gdrops = '0';
      var drops = 'None';
      if (json[round].enemy[enemy].children[part].drop_item_list.length > 0) {
        for (var itemIndex in json[round].enemy[enemy].children[part].drop_item_list) {
          var item = json[round].enemy[enemy].children[part].drop_item_list[itemIndex];

          if (item.type == 11) {
            gdrops = item.amount;
          } else {
            drops = inventory[item.item_id] + ' (' + item.rarity + '*)';
          }
        }
       }

	    rows.push(gdrops);
      rows.push(drops);
```

to:
```
      var drops = [];
      if (json[round].enemy[enemy].children[part].drop_item_list.length > 0) {
        for (var itemIndex in json[round].enemy[enemy].children[part].drop_item_list) {
          var item = json[round].enemy[enemy].children[part].drop_item_list[itemIndex];

          if (item.type == 11) {
            drops.push('Gold: ' + item.amount);
          } else {
            drops.push(inventory[item.item_id] + ' (' + item.rarity + '*)');
          }
        }
       }

      rows.push(drops.join(', '));
```

Untested, but with this we won't lose drops and only need one column.

**Comment by ThauEx** [comment]
I found something interesting for you:
```
DROP_ITEM_TYPE: {
    GIL: 11,
    POTION: 21,
    HI_POTION: 22,
    X_POTION: 23,
    ETHER: 31,
    TURBO_ETHER: 32,
    TREASURE: 41,
    ORB: 51,
    EVENT_ITEM: 61
},
```

**Comment by KHShadowrunner** [comment]
Sorry, work has been pretty crazy as of late. I'll see what I can do this weekend to incorporate it :)

**Comment by ThauEx** [comment]
Sry, have not seen your edit :D
Code looks good, but can you add a new mapping file for item types and use it for the potions?
And what else is missing after that? Boss drops?

**Comment by KHShadowrunner** [comment]
I'll look into the mapping file. The only other thing  I think we're missing is: What to catch if we don't have a match (for new gear that gets added), and those weird boss mobs where the initial boss doesn't actually drop it. We might want to see if we can also list out those 'phases' like the summons rather than the original target. But htat might be a whole new adventure.

**Comment by ThauEx** [comment]
Any new progress?
I had a look on your multiple phase boss, and noticed, that there is just a miss placed bracket.
```
 Round: 1   lvl   uid   HP              atk     def     matk    mdef    acc     eva    spd     extra      drops
 Grothia    107   201   53697/53697     343>1   423>1   395>1   353>1   100>1   70>1   100>1   Debuffed
 Spathi     107   202   89495/89495     361>1   281>1   416>1   353>1   100>1   70>1   100>1   Debuffed
 Isaaru     107   203   162623/162623   361>1   320>1   380>1   320>1   100>1   70>1   100>1   Debuffed   Greater Non-Elemental Orb (4*)
 Pterya     107   204   71596/71596     325>1   423>1   375>1   529>1   100>1   70>1   100>1   Debuffed
```

Here is my file: https://gist.github.com/ThauEx/3d2126d72985c62a3342
So now, only the potion mapping is missing.

**Comment by KHShadowrunner** [comment]
Ok, whipped up a quick file and modifed the select statement to simply list out the potion, as if we're looking at a list we no longer have to determine type. It's very basic for now because: ID 23 and ID 32 I have never seen. I dont know what color the potions are, nor how they behave (if 21 is 10% hp, and 22 is 15% hp, I assume 23 is 20% hp, but can't know for sure). But I haven't heard of either of them dropping yet. Also, I have never seen an item or orb drop as an end of round reward,  same with event item, so even though they're in the list - I doubt they'll ever be called. If they are, we'll need to come up with a way to ID the item. This  will require a dump to see how the item is actually listed out. I could guess, but the way it is now will work for the forseeable future until those situations come into play.

**Comment by ThauEx** [comment]
Thanks for your work.

**Pull request merged**
