### PR TITLE
Update buddy.js

### PR DESCRIPTION
**Pull request by Weirion**
Adding MND.

### CODE REVIEW

**Comment by ThauEx** [comment]
Can you add a default value to the configuration?

**Comment by Weirion** [comment]
Yes, I'm adding all right now!

**Comment by Weirion** [comment]
Ok, done! I tested all changes myself in 0.53 and they work.
According to this https://www.dropbox.com/s/ndbkwcvhfd20os5/battle-August-2015.js?dl=0 , Stun is called STAN in the game code, so I added it as such.

**Comment by Weirion** [comment]
Ack, my bad, fixed!

**Comment by KHShadowrunner** [comment]
Is there a need to 0 out the enemy's mnd as well? I see it is a stat, just curious if we want to address it or not.

**Comment by Weirion** [comment]
There are enemies like Holy Dragon that use, well, Holy, so its just a precaution.

**Pull request merged**
