### PR TITLE
Add cert as a command line argument

### PR DESCRIPTION
**Pull request by jdel**
Allows passing --cert XXXX to define cert port at runtime.

### CODE REVIEW

**Comment by ThauEx** [comment]
I suggest to use `cert-port`/`CERT_PORT`, because `cert`sound like you want to pass a custom certificate.

**Comment by jdel** [comment]
Shall I change port into proxy-port and PROXY_PORT for naming consistency ?

**Comment by ThauEx** [comment]
I don't think we need that, because the software name already contains proxy, so it is obvious that the port is for the proxy.

**Comment by jdel** [comment]
Ok, change has been done. 

The reason for this PR is that I made a docker container, and it would be handy to be able to set cert-port via the command line to change the port at runtime instead of the config file.

You can find the docker container sources in [my repo](https://github.com/jdel/docker-ffrk-proxy) and the image on the [Docker Hub](https://hub.docker.com/r/jdel/ffrk-proxy/).

I have been running this container for a few days now and it works pretty well. Any recommendations would be appreciated.

I will be updating the container as soon as this PR is merged and put into a release.

**Pull request merged**
