### PR TITLE
Update buddy.js - Experimenting with Hit-All

### PR DESCRIPTION
**Pull request by KHShadowrunner**
Configured Materia to be set to the "Zealot" Materia and pushed the new "Attack" that the Zealot materia would add if actually equipped. Overrides the Attack default action. Produces Hit-All

### CODE REVIEW

**Comment by ThauEx** [comment]
What is the status of this feature?

**Comment by jdel** [comment]
I have been using this for ages in my Synology package, and as far as I can tell, it works flawlessly. I think it should be merged, unless somebody sees a reason not to?

**Comment by KHShadowrunner** [comment]
I could have sworn I replied - lol.

It works, just fine. You might want to re-code it so that it works with the new code format (maybe add a new RecordMateria.js file that has the code for RMs that we really like? IDK), but if you copy and paste it in it works with np. I accidentally left the cast time at it's regular value, you can change that to something smaller (or you can put it before the code that sets all cast times to 10 like I usually do). 

You can also supposedly change it to do a group attack and attack twice (something about setting arg2 = number of hits! What a cool find that I havent' confirmed). But if you have more than one char that's really not necessary.

Yeah it works just fine.

**Comment by ThauEx** [comment]
Okay, thanks. Can you please create RecordMateria.js filter?

**Comment by KHShadowrunner** [comment]
I need to rebuild this whole thing - I've been playing around a LOT with my configuration. Let me see if I can find a way to tidy it up via github rather than a whole new pull

**Pull request closed without merging**
