### PR TITLE
Add new 4* magicites

### PR DESCRIPTION
**Pull request by jdel**
Implements https://github.com/ThauEx/ffrk-proxy/issues/103

I will add the realm like 3* magicites in a later commit.

### CODE REVIEW

**Comment by ThauEx** [comment]
Thank you.

**Comment by jdel** [comment]
@ThauEx : Sorry I should have added a WIP tag, the PR was not ready to merge. Any chance you can do a rollback ? Otherwise I can create a new one.

**Comment by ThauEx** [comment]
As long as I don't create a new release, we should be safe.

**Comment by jdel** [comment]
Ok, I will make a new PR later on with the missing details.

**Pull request merged**
